
version: "3.8"
   
services:
  web:
    build: .
    command: flask run
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

volumes:
  postgres_data: