
version: "3.8"
   
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
      
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

  redis:
    image: redis
    volumes:
      - 'redis_data:/var/lib/redis/data'


  worker:
    build: .
    env_file:
      - ./.env.dev
    entrypoint: ["celery"]
    command: ["-A", "app.celery", "worker", "--loglevel=INFO"]
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis


volumes:
  postgres_data:
  redis_data: